name: heart-disease-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
    - mlflow==2.19.0
    - pandas==2.1.4
    - numpy==1.26.2
    - scikit-learn==1.3.2
    - dagshub==0.3.5