name: MLflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow
        pip install -r MLProject/requirements.txt
    
    - name: Run MLflow Project
      run: |
        mlflow run MLProject/ -P data_dir=heart_preprocessing
    
    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: mlruns/
    
    - name: Build and Push Docker Image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker build -t yusufarist/heart-disease-prediction:latest .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push yusufarist/heart-disease-prediction:latest
