name: MLflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2.4.2
      
    - name: Set up Python
      uses: actions/setup-python@v2.3.2
      with:
        python-version: '3.12.7'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mlflow
        pip install -r MLProject/requirements.txt
    
    - name: Run MLflow Project
      run: |
        mlflow run MLProject/ -P data_dir=heart_preprocessing
    
    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v2.3.1
      with:
        name: model-artifacts
        path: mlruns/
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Docker Image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: yusufarist/heart-disease-prediction:latest
